# Manually reasoned WHO ATC first-level group for every one of the 359 medicines on the WHO
# Model List of Essential Medicines for Children (EMLc), 9th List 2023. Classified individually
# using standard ATC/pharmacological knowledge (not inherited automatically from the long-tail
# drug-name map used for Normalized_Drugs, since a medicine can carry a different primary ATC
# classification in its EMLc-listed context than in general trial-intervention text -- e.g.
# naloxone/protamine are classified here as V03 antidotes, matching their EMLc listing, even
# though they appear as opioid/anaesthesia-adjacent agents in ordinary trial text).
# 14 groups only: A B C D G H J L M N P R S V

EMLC_ATC_MAP = {
"abacavir + lamivudine":"J","acetic acid":"D","acetylcysteine":"V","acetylsalicylic acid":"N",
"aciclovir":"J","adalimumab":"L","albendazole":"P","alcohol based hand rub":"D",
"all-trans retinoid acid (atra)":"L","allopurinol":"M","amikacin":"J","amitriptyline":"N",
"amodiaquine":"P","amoxicillin":"J","amoxicillin + clavulanic acid":"J","amphotericin b":"J",
"ampicillin":"J","ansuvimab":"J","anti-rabies immunoglobulin":"J","anti-rabies monoclonal antibodies":"J",
"anti-tetanus immunoglobulin":"J","antivenom immunoglobulin":"J","aprepitant":"A",
"arsenic trioxide":"L","artemether":"P","artemether + lumefantrine":"P","artesunate":"P",
"artesunate + amodiaquine":"P","artesunate + mefloquine":"P",
"artesunate + pyronaridine tetraphosphate":"P","ascorbic acid":"A","asparaginase":"L",
"atoltivimab + maftivimab + odesivimab":"J","atropine":"A","azathioprine":"L","azithromycin":"J",
"barium sulfate":"V","bcg vaccine":"J","bedaquiline":"J","benzathine benzylpenicillin":"J",
"benznidazole":"P","benzoyl peroxide":"D","benzyl benzoate":"P","benzylpenicillin":"J",
"betamethasone":"H","bleomycin":"L","budesonide":"R","bupivacaine":"N","caffeine citrate":"N",
"calamine":"D","calcipotriol":"D","calcium folinate (leucovorin calcium)":"V",
"calcium gluconate":"A","carbamazepine":"N","carboplatin":"L","cefalexin":"J","cefazolin":"J",
"cefixime":"J","cefotaxime":"J","ceftazidime":"J","ceftazidime + avibactam":"J",
"ceftolozane + tazobactam":"J","ceftriaxone":"J","cefuroxime":"J","charcoal, activated":"V",
"chloramphenicol":"J","chlorhexidine":"D","chlorine base compound":"D","chloroquine":"P",
"chloroxylenol":"D","cholera vaccine":"J","ciclosporin":"L","ciprofloxacin":"J",
"cisplatin":"L","clarithromycin":"J","clindamycin":"J","clofazimine":"J","cloxacillin":"J",
"coagulation factor ix":"B","coagulation factor viii":"B","coal tar":"D",
"colecalciferol":"A","colistin":"J","cryoprecipitate, pathogen-reduced":"B","cyclizine":"A",
"cyclophosphamide":"L","cycloserine":"J","cytarabine":"L","dacarbazine":"L","daclatasvir":"J",
"daclatasvir + sofosbuvir":"J","dactinomycin":"L","dapsone":"J","darunavir":"J","dasatinib":"L",
"daunorubicin":"L","deferasirox":"V","deferoxamine":"V","delamanid":"J","dengue vaccine":"J",
"desmopressin":"H","dexamethasone":"H","dextran 70":"B","diazepam":"N","diazoxide":"H",
"diethylcarbamazine":"P","digoxin":"C","dihydroartemisinin + piperaquine phosphate":"P",
"diloxanide":"P","dimercaprol":"V","diphtheria antitoxin":"J","diphtheria vaccine":"J",
"docusate sodium":"A","dolutegravir":"J","dopamine":"C","doxorubicin":"L",
"doxorubicin (as pegylated liposomal)":"L","doxycycline":"J","eflornithine":"P",
"enalapril":"C","enoxaparin":"B","entecavir":"J","epinephrine (adrenaline)":"C",
"equine rabies immunoglobulin":"J","erythromycin":"J","erythropoiesis-stimulating agents":"B",
"ethambutol":"J","ethanol":"V","ethionamide":"J","ethosuximide":"N","etoposide":"L",
"everolimus":"L","ferrous salt":"B","fexinidazole":"P","filgrastim":"L","fluconazole":"J",
"flucytosine":"J","fludrocortisone":"H","fluorescein":"S","fluorouracil":"L","folic acid":"B",
"fomepizole":"V","fosfomycin":"J","frozen plasma":"B","furosemide":"C","gentamicin":"J",
"glass ionomer cement":"V","glecaprevir + pibrentasvir":"J","glucagon":"H","glucose":"B",
"glucose with sodium chloride":"B","glutaral":"D",
"haemophilus influenzae type b vaccine":"J","halothane":"N","heparin sodium":"B",
"hepatitis a vaccine":"J","hepatitis b vaccine":"J","human papilloma virus (hpv) vaccine":"J",
"hydrochlorothiazide":"C","hydrocortisone":"H","hydroxocobalamin":"V",
"hydroxycarbamide (hydroxyurea)":"L","hydroxychloroquine":"P","hyoscine hydrobromide":"A",
"ibuprofen":"N","ifosfamide":"L","imatinib":"L","influenza vaccine":"J",
"insulin injection (soluble)":"A","intermediate-acting insulin":"A",
"intraperitoneal dialysis solution":"V","iodine":"D","irinotecan":"L","isoflurane":"N",
"isoniazid":"J","isoniazid + pyrazinamide + rifampicin":"J",
"isoniazid + pyridoxine + sulfamethoxazole + trimethoprim":"J","isoniazid + rifampicin":"J",
"isoniazid + rifapentine":"J","itraconazole":"J","ivermectin":"P",
"japanese encephalitis vaccine":"J","ketamine":"N","lactulose":"A","lamivudine":"J",
"lamivudine + zidovudine":"J","lamotrigine":"N","levamisole":"P","levetiracetam":"N",
"levofloxacin":"J","levothyroxine":"H","lidocaine":"N","lidocaine + epinephrine (adrenaline)":"N",
"linezolid":"J","long-acting insulin analogues":"A","lopinavir + ritonavir":"J","loratadine":"R",
"lorazepam":"N","lugol's solution":"H","mannitol":"B","measles vaccine":"J","mebendazole":"P",
"mefloquine":"P","meglumine antimoniate":"P","melarsoprol":"P","meningococcal meningitis vaccine":"J",
"mercaptopurine":"L","meropenem":"J","mesna":"L","metformin":"A","methadone":"N",
"methimazole":"H","methotrexate":"L","methylprednisolone":"H","metoclopramide":"A",
"metronidazole":"J","micafungin":"J","miconazole":"D","midazolam":"N","miltefosine":"P",
"morphine":"N","moxifloxacin":"J","multiple micronutrient powder":"A","mumps vaccine":"J",
"mupirocin":"D","naloxone":"V","natamycin":"S","neostigmine":"N","niclosamide":"P",
"nifurtimox":"P","nilotinib":"L","nitrofurantoin":"J","nitrous oxide":"N",
"normal immunoglobulin":"J","nystatin":"J","ofloxacin":"J","omeprazole":"A","ondansetron":"A",
"oral rehydration salts":"A","oseltamivir":"J","oxaliplatin":"L","oxamniquine":"P","oxygen":"R",
"p-aminosalicylate sodium":"J","paclitaxel":"L","pancreatic enzymes":"A",
"paracetamol (acetaminophen)":"N","paromomycin":"P","pegaspargase":"L","pegfilgrastim":"L",
"pentamidine":"P","permethrin":"P","pertussis vaccine":"J","phenobarbital":"N",
"phenoxymethylpenicillin":"J","phenytoin":"N","phytomenadione":"B",
"piperacillin + tazobactam":"J","platelets":"B","pneumococcal vaccine":"J",
"podophyllum resin":"D","poliomyelitis vaccine":"J","polymyxin b":"J","potassium chloride":"A",
"potassium iodide":"H","potassium permanganate":"D","povidone iodine":"D","praziquantel":"P",
"prednisolone":"H","primaquine":"P","procaine benzylpenicillin":"J","procarbazine":"L",
"proguanil":"P","propofol":"N","propranolol":"C","propylthiouracil":"H","prostaglandin e1":"C",
"protamine sulfate":"V","pyrantel":"P","pyrazinamide":"J","pyridostigmine":"N","pyridoxine":"A",
"pyrimethamine":"P","quinine":"P","rabies vaccine":"J","raltegravir":"J","ranitidine":"A",
"rasburicase":"V","ready-to-use therapeutic food":"A","realgar-indigo naturalis formulation":"L",
"red blood cells":"B","resin-based composite (high-viscosity)":"V",
"resin-based composite (low-viscosity)":"V","retinol":"A","ribavirin":"J","riboflavin":"A",
"rifampicin":"J","rifapentine":"J","ritonavir":"J","rituximab":"L","rotavirus vaccine":"J",
"rubella vaccine":"J","salbutamol":"R","salicylic acid":"D","selenium sulfide":"D",
"senna":"A","sevoflurane":"N","silver diamine fluoride":"D","silver sulfadiazine":"D",
"sodium calcium edetate":"V","sodium chloride":"B","sodium hydrogen carbonate":"B",
"sodium lactate, compound solution":"B","sodium stibogluconate":"P","sofosbuvir":"J",
"sofosbuvir + velpatasvir":"J","spironolactone":"C","streptomycin":"J","succimer":"V",
"sulfadiazine":"J","sulfadoxine + pyrimethamine":"P","sulfamethoxazole + trimethoprim":"J",
"suramin sodium":"P","surfactant":"R","suxamethonium":"M","tacrolimus":"L","terbinafine":"J",
"tetanus vaccine":"J","tetracaine":"N","tetracycline":"J","thiamine":"A",
"tick-borne encephalitis vaccine":"J","tioguanine":"L","triamcinolone hexacetonide":"H",
"triclabendazole":"P","trimethoprim":"J","tropicamide":"S",
"tuberculin, purified protein derivative (ppd)":"V","typhoid vaccine":"J","urea":"D",
"valganciclovir":"J","valproic acid (sodium valproate)":"N","vancomycin":"J",
"varicella vaccine":"J","vecuronium":"M","vinblastine":"L","vincristine":"L","vinorelbine":"L",
"voriconazole":"J","warfarin":"B","water for injection":"V","whole blood":"B",
"xylometazoline":"R","yellow fever vaccine":"J","zidovudine":"J","zinc sulfate":"A",
"fluoride":"A","griseofulvin":"J","nevirapine":"J",
}
