"""
Keyword dictionary mapping research-topic categories (anchored to ICD-10 disease
chapters, plus 1 procedure-context category) to the disease/condition-text keyword
patterns used to classify each trial. Extracted from
analysis/rebuild_all_consolidated_v2.py (TOPIC_KEYWORDS).
"""

TOPIC_KEYWORDS = {
    'Perioperative pain, sedation, anaesthesia & procedural care': ['pain', 'sedation', 'emergence agitation', 'anesthesia', 'anaesthesia', 'analgesia', 'tonsillectomy', 'tonsillopharyngitis', 'adenotonsillectomy', 'adenoidectomy', 'dental extraction', 'elective surgery', '\\bsurgery\\b', 'hernia', 'neuromuscular blockade', 'laceration', 'circumcision', 'venipuncture', 'lumbar puncture', 'endoscopy', 'colonoscopy', 'intubation', 'premedication', 'infraumbilical', 'surgeries'],
    'Neonatology (perinatal/neonatal-specific)': ['respiratory distress syndrome', 'patent ductus arteriosus', 'bronchopulmonary dysplasia', '\\bapnea\\b', 'retinopathy of prematurity', 'hyperbilirubinemia', 'jaundice', 'intraventricular hemorrhage', 'hypoxic ischaemic encephalopathy', 'hypoxic ischemic encephalopathy', 'preterm birth', 'transient tachypnea', 'asphyxia', 'feed intolerance', 'necrotizing enterocolitis', 'neonat', 'newborn'],
    'Respiratory (non-neonatal)': ['\\basthma\\b', 'bronchiolitis', 'respiratory tract infection', 'pneumonia', 'cystic fibrosis', 'wheezing', 'chronic lung disease', 'respiratory disease', '\\bcroup\\b', 'respiratory syncytial virus', '\\brsv\\b', 'influenza', '\\bcough\\b', 'sinusitis', 'common cold', 'upper respiratory'],
    'Neuropsychiatric & developmental': ['\\badhd\\b', 'attention deficit', 'autism', '\\banxiety\\b', 'depression', 'bipolar', 'hyperactivity', 'tourette', 'obsessive compulsive', 'stress disorder', 'schizophrenia', 'conduct disorder', 'cerebral palsy', '\\bseizure', 'convulsion', 'spasm', 'migraine', 'sleep disorder', 'insomnia', 'anorexia nervosa', 'disruptive behavior', 'minimal brain dysfunction', 'withdrawal movement', 'neonatal abstinence', 'behavior management', 'behaviour management'],
    'Infectious disease (systemic/parasitic)': ['\\bmalaria\\b', '\\bhiv\\b', 'bacterial meningitis', '\\bsepsis\\b', 'hepatitis', 'typhoid', 'schistosomiasis', 'giardiasis', 'hookworm', 'trichuris', 'encephalitis', 'tuberculosis', 'chickenpox', 'varicella', 'measles', 'dengue', 'skin infection', 'impetigo', 'trachoma', 'tinea', 'molluscum', '\\binfection\\b', 'shigellosis', 'ascariasis', 'dysentery', 'cholera', 'pertussis', 'rotavirus', 'tetanus'],
    'Oncology & haematology': ['leukemia', 'leukaemia', '\\bcancer\\b', 'anemia', 'anaemia', 'febrile neutropenia', 'neuroblastoma', 'sickle cell', 'purpura', 'lymphoma', 'tumor', 'tumour', 'thalassemia', 'thalassaemia', 'hodgkin', 'rhabdomyosarcoma', 'medulloblastoma', 'wilms', 'sarcoma', 'glioma', 'hemophilia', 'haemophilia'],
    'Endocrine, growth & metabolic': ['\\bdiabetes\\b', 'growth hormone', 'short stature', '\\bobesity\\b', '\\bpuberty\\b', 'turner syndrome', 'prader-willi', 'hypercholesterolaemia', 'hypercholesterolemia', 'constitutional delay of growth', 'thyroid', 'metabolic', 'hyperglycemia', 'hyperglycaemia', 'polycystic ovary', 'hypophosphatemia', 'hypophosphataemia'],
    'ENT, dental & craniofacial': ['otitis media', 'tonsillitis', 'adenoid hypertrophy', '\\bcaries\\b', 'cleft lip', 'cleft palate', 'craniosynostosis', 'dental procedure'],
    'Gastrointestinal': ['\\bvomiting\\b', '\\bdiarrhea\\b', '\\bdiarrhoea\\b', 'gastroesophageal reflux', 'appendicitis', '\\bcolitis\\b', 'crohn', 'functional constipation', 'gastroenteritis', 'helicobacter pylori', 'inflammatory bowel', 'emesis', 'chronic constipation', 'non-alcoholic fatty liver', 'intestinal helminth', 'infantsile colic', 'infantile colic', '\\bcolic\\b', 'liver transplant'],
    'Nephrology & urology': ['nephrotic syndrome', 'chronic kidney disease', 'vesicoureteric reflux', 'pyelonephritis', 'urinary tract infection', '\\benuresis\\b', 'chronic renal failure', 'hypospadias', 'cryptorchidism', 'phimosis'],
    'Dermatology, rheumatology & musculoskeletal': ['juvenile idiopathic arthritis', 'juvenile rheumatoid arthritis', 'plaque psoriasis', 'eczema', 'atopic dermatitis', 'hemangioma', 'osteogenesis imperfecta', 'idiopathic scoliosis', 'scoliosis', 'duchenne muscular dystrophy', 'psoriasis'],
    'Ophthalmology': ['\\bmyopia\\b', 'strabismus', 'vernal keratoconjunctivitis', 'amblyopia', '\\bcataract\\b', 'conjunctivitis'],
    'Cardiology': ['congenital heart defect', 'cardiac disease', 'tetralogy of fallot', 'kawasaki disease', '\\bhypertension\\b', 'arrhythmia'],
    'Allergy & rhinitis': ['\\brhinitis\\b', 'allergic rhinitis', 'urticaria', '\\ballerg', 'acne vulgaris', '\\bacne\\b', 'exercise-induced bronchoconstriction', 'bronchoconstriction'],
    'General/nonspecific, trauma, burns & critical care': ['\\bfever\\b', 'no specific disease', 'severe burns', '\\bburns?\\b', '\\binjury\\b', 'head injury', 'kidney injury', 'hypotension', 'inflammation', '\\btrauma\\b', 'shock', 'critical illness'],
}
